sm_app/sm_project/urls.py
from django.contrib import admin
from django.urls import include, path


# The urls that link to each app in the project
urlpatterns = [
    path('', include('sm_project.user_app.urls')),
    path('checklists/', include('sm_project.cl_app.urls')),
    path('admin/', admin.site.urls),
]

sm_app/sm_project/user_app/urls.py
from django.urls import path

from sm_project.user_app import views


app_name = 'user_app'
# The urls that are a part of the app, "user_app"
urlpatterns = [
    path("", views.login_request, name="login"),
    path("register/", views.register_request, name="register")
]

sm_app/sm_project/user_app/models.py
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
from django.db import models
from django.shortcuts import get_object_or_404


class UserManager(BaseUserManager):
    """A custom user manager class for the new user class.

    Methods
    -------
    create_user(self, email, name, password=None)
        Creates a new user in the database using the given email, name and password.
    create_superuser(self, email, name, password)
        Creates a new admin user in the database using the given email, name and password.
    """
    def create_user(self, email, name, password=None):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            name=name,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, name, password):
        user = self.create_user(
            email,
            password=password,
            name=name,
        )
        user.admin = True
        user.save(using=self._db)
        return user

class User(AbstractBaseUser):
    """A class that will be used as a replacement for the base user class.

    Attributes
    -------
    username: None
        Sets the default username of the user class as none.
    email: EmailField
        The email of the user. This attribute has a limit of 255 characters and must be unique.
    name: CharField
        The name of the user. This attribute has a limit of 70 characters.
    admin: BooleanField
        Defines whether the user is an admin user or not.
    objects: class
        The user manager class that the user class uses

    Methods
    -------
    __str__(self)
        Returns the email of the user.
    is_staff(self)
        Returns whether the user is considered an staff member.
    is_admin(self)
        Returns whether the user is considered an admin.
    has_temp_checklist(self)
        Returns whether the checklist that is used to store temporary checklist items as part of checklist creation exists.
        See add_checklist(request) and add_temp_item(request) in cl_app/views.py for more.
    get_temp_checklist(self)
        Returns the checklist that is used to store temporary checklist items as part of checklist creation.
        See add_checklist(request) and add_temp_item(request) in cl_app/views.py for more.
    """
    username = None
    email = models.EmailField(max_length=255, unique=True)
    name = models.CharField(max_length=70)
    admin = models.BooleanField(default=False)
    objects = UserManager()

    # Sets the attribute used as the username to the email
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

    def __str__(self):
        return f"{self.name} - {self.email}"

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True
        
    @property
    def is_staff(self):
        return self.admin
    
    @property
    def is_admin(self):
        return self.admin
    
    def has_temp_checklist(self):
        return self.creator.filter(checklist_title=(f"Temp{self.id}")).exists()
    
    def get_temp_checklist(self):
        return get_object_or_404(self.creator, checklist_title=(f"Temp{self.id}"))

sm_app/sm_project/user_app/forms.py
from django.contrib.auth.forms import UserCreationForm

from sm_project.user_app.models import User


class NewUserForm(UserCreationForm):
    """Organises how the User creation form will be set up"""
    class Meta:
        model = User
        fields = ['name', 'email', 'password1', 'password2']
    
    def __init__(self, *args, **kwargs):
        super(NewUserForm, self).__init__(*args, **kwargs)
        self.fields['password2'].label = "Password Confirmation"

sm_app/sm_project/user_app/views.py
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.views.decorators.csrf import csrf_protect
from django.shortcuts import render, redirect

from sm_project.user_app.forms import NewUserForm


@csrf_protect
def login_request(request):
    """Renders a view of the login screen and authenticates that the user's details are in the system."""
    if request.method == "POST":
        login_form = AuthenticationForm(request, request.POST)
        if login_form.is_valid():
            email = login_form.cleaned_data.get('username')
            password = login_form.cleaned_data.get('password')
            user = authenticate(email=email, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {email}.")
                return redirect('cl_app:user_checklists')
            else:
                messages.error(request, "Invalid email or password.")
        else:
            messages.error(request, "Invalid form.")
    else:
        login_form = AuthenticationForm()
    return render(request, "user_app/login.html", {"login_form": login_form})

def register_request(request):
    """Renders a view of the user register screen and creates a new user upon the form being submitted."""
    if request.method == "POST":
        register_form = NewUserForm(data=request.POST)
        if register_form.is_valid():
            user = register_form.save()
            login(request, user)
            messages.success(request, "Account successfully created.")
            return redirect("cl_app:user_checklists")
    else:
        register_form = NewUserForm()
    return render(request, "user_app/register.html", {"register_form": register_form})

sm_app/sm_project/user_app/templates/user_app/base.html
<!doctype html>
<html lang="en" style="height:100%;">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <title>Scientific Method Checklists</title>
</head>
<body style="background-color:AliceBlue; height:100%; display:flex; flex-direction:column;">
  <div class="container bg-white px-4" style="flex-grow:1">
      <div class="row justify-content-center">
        <div class="col">
          <h1 class="mt-2">Scientific Method Checklists</h1>
          <hr class="mt-0 mb-4">
          {% block content %}
          {% endblock %}
        </div>
      </div>
  </div>
</body>
</html>

sm_app/sm_project/user_app/templates/user_app/login.html
{% extends 'user_app/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <h2>Log In</h2>
  <form id="login" method="POST">
    {% csrf_token %}
    {{ login_form|crispy }}
  </form>
  <div class="form-row">
    <div class="col text-center pb-4">
      <button type="submit" form="login" class="btn btn-primary">Log In</button>
    </div>
    <div class="col text-center pb-4">
      <a href="{% url 'user_app:register' %}"><button class="btn btn-primary ">Register</button></a>
    </div>
  </div>
{% endblock %}

sm_app/sm_project/user_app/templates/user_app/register.html
{% extends 'user_app/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <h2>Create A User Account</h2>
  <form id="register" method="POST">
    {% csrf_token %}
    {{ register_form|crispy }}
  </form>
  <div class="form-row">
    <div class="col text-center pb-2">
      <button type="submit" form="register" class="btn btn-primary">Create Account</button>
    </div>
  </div>
  <div class="form-row">
    <div class="col text-center pb-4">
      <a href="{% url 'user_app:login' %}"><button class="btn btn-secondary">Back</button></a>
    </div>
  </div>
{% endblock %}