sm_app/sm_project/cl_app/urls.py
from django.conf import settings
from django.contrib.auth.views import LogoutView
from django.urls import path

from sm_project.cl_app import views


app_name = 'cl_app'
# The urls that are a part of the app, "cl_app"
urlpatterns = [
    path('', views.checklist_index, name="user_checklists"),
    path('add_checklist/', views.add_checklist, name="add_checklist"),
    path('add_checklist/add_item/', views.add_temp_item, name="add_temp_item"),
    path('add_checklist/template/', views.use_template, name="use_template"),
    path('add_checklist/remove_item<int:item_id>/', views.remove_temp_item, name="remove_temp_item"),
    path('leave_checklist<int:checklist_id>/', views.leave_checklist, name="leave_checklist"),
    path('remove_checklist<int:checklist_id>/', views.remove_checklist, name="remove_checklist"),
    path('logout/', LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name="logout"),
    path('checklist<int:checklist_id>/', views.checklist_view, name="checklist"),
    path('checklist<int:checklist_id>/document/', views.open_document, name="open_document"),
    path('item<int:item_id>/update/', views.update_item_status, name="update_item_status"),
    path('item<int:item_id>/feedback/', views.send_feedback, name="send_feedback"),
    path('checklist<int:checklist_id>/edit/', views.edit_checklist, name="edit_checklist"),
    path('checklist<int:checklist_id>/add/', views.add_item, name="add_item"),
    path('remove_item<int:checklistitem_id>/', views.remove_item, name="remove_item"),
]

sm_app/sm_project/urls.py
from django.contrib import admin
from django.urls import include, path


# The urls that link to each app in the project
urlpatterns = [
    path('', include('sm_project.user_app.urls')),
    path('checklists/', include('sm_project.cl_app.urls')),
    path('admin/', admin.site.urls),
]

sm_app/sm_project/cl_app/models.py
from django.conf import settings
from django.contrib import admin
from django.db import models


User = settings.AUTH_USER_MODEL

class Checklist(models.Model):
    """A model class used to represent the checklists.

    Attributes
    ----------
    checklist_title: CharField
        The title of the checklist.
    document: URLField
        The link to the document the checklist is attributed to.
        This attribute is optional.
    creator: ForeignKey
        The creator of the checklist.
    checklist_users: ManyToManyField
        A field that stores the many to many relationships between the checklists and the users.
    researchers: ManyToManyField
        A field that stores the many to many relationships between the checklists and the researchers.
    reviewers: ManyToManyField
        A field that stores the many to many relationships between the checklists and the researchers.

    Methods
    -------
    __str__(self)
        Prints the title of the checklist
    creator_name(self):
        Returns the name of the creator of the checklist.
    researcher_emails(self)
        Returns a list of all of the researchers attached to a checklist.
    reviewer_emails(self)
        Returns a list of all of the reviewers attached to a checklist.
    template_checklist(self, item_set)
        Changes a checklist's list of items to a template given by item_set.
    """
    checklist_title = models.CharField(verbose_name="Checklist", max_length=200)
    document = models.URLField(verbose_name="Document Link", max_length=150, blank=True)
    creator = models.ForeignKey(User, verbose_name="Creator Email", on_delete=models.CASCADE, related_name='creator')
    checklist_users = models.ManyToManyField(User, verbose_name="Checklist Users")
    researchers = models.ManyToManyField(User, related_name='researchers')
    reviewers = models.ManyToManyField(User, related_name='reviewers', blank=True)

    def __str__(self):
        return self.checklist_title
    
    @property
    @admin.display(description="Creator")
    def creator_name(self):
        return self.creator.name
    
    def researcher_emails(self):
        email_list = list()
        for user in self.researchers.all():
            email_list.append(user.email)
        return email_list
    
    def reviewer_emails(self):
        email_list = list()
        for user in self.reviewers.all():
            email_list.append(user.email)
        return email_list
    
    def template_checklist(self, item_list):
        self.checklistitem_set.all().delete()
        item = ChecklistItem(item_checklist=self, item_title=item_list[0], item_status=3)
        item.save()
        for it in range(len(item_list[:-1])):
            prev_item = item
            item = ChecklistItem(item_checklist=self, item_title=item_list[it+1], item_status=3)
            item.save()
            item.dependencies.add(prev_item)
        return self.checklistitem_set.all()

class ChecklistItem(models.Model):
    """A model class used to represent the items in each of the checklists.

    Attributes
    ----------
    item_checklist: ForeignKey
        The checklist that the checklist item is connected to.
    item_title: CharField
        The title of the checklist item
    item_status: IntegerField
       The status of an item as an integer. The available choices can be found in the class, Status.
       The default status is INCOMPLETE or 3.
    time_estimate: DateField
        The estimated date that the checklist item is expected to be marked as complete by.
        This attribute is optional.
    depending_items: ManyToManyField
        The items that the item is the dependant on being marked as completed before they can be requested for review.
        This attribute is optional.

    Methods
    -------
    __str__(self)
        Prints the title of the checklist item.
    get_status(self)
        Returns the status of the checklist item.
    get_dependencies(self)
        Returns a string of all the items that this item is dependant on.
    dependencies_completed(self)
        Checks whether all of the item's dependancies have been marked as complete.
    """
    class Status(models.IntegerChoices):
        # A class that stores the available choices for the IntegerField, item_status
        COMPLETED = 1, 'Completed'
        FOR_REVIEW = 2, 'For Review'
        INCOMPLETE = 3, 'Incomplete'

    item_checklist = models.ForeignKey(Checklist, verbose_name="Checklist", on_delete=models.CASCADE)
    item_title = models.CharField(verbose_name="Checklist Item", max_length=200)
    item_status = models.IntegerField(verbose_name="Status", choices=Status.choices, default=Status.INCOMPLETE)
    time_estimate = models.DateField(verbose_name="Estimated Completion Date", null=True, blank=True)
    depending_items = models.ManyToManyField("self", related_name="dependencies", blank=True, symmetrical=False)

    def __str__(self):
        return self.item_title

    def get_status(self):
        return self.Status(self.item_status).label
    
    def get_dependencies(self):
        dependencies = ""
        if self.dependencies.exists():
            for dependency in list(self.dependencies.all())[:-1]:
                dependencies += f"{dependency}, "
            dependencies += f"{list(self.dependencies.all())[-1]}"
        return dependencies
    
    def dependencies_completed(self):
        if self.dependencies.exists():
            for dependency in self.dependencies.all():
                if dependency.item_status != 1:
                    return False
        return True

sm_app/sm_project/cl_app/views.py
from django import forms
from django.contrib.auth.decorators import login_required
from django.core.exceptions import NON_FIELD_ERRORS
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404, redirect

from sm_project.cl_app.forms import ChecklistForm, ChecklistItemForm, FeedbackForm
from sm_project.cl_app.models import Checklist, ChecklistItem
from sm_project.settings import EMAIL_HOST_USER, TEMPLATE_LIST


@login_required(login_url='user_app:login')
def checklist_index(request):
    """Renders a view of all the checklists that the user has."""
    if request.user.has_temp_checklist():
        request.user.get_temp_checklist().delete()
    return render(request, 'cl_app/checklist_index.html', {'user_checklists': request.user})
    
@login_required(login_url='user_app:login')
def add_checklist(request):
    """Renders a view of the add checklist screen and allows the user to create a new checklist."""
    if request.user.has_temp_checklist():
        temp_checklist = request.user.get_temp_checklist()
    else:
        temp_checklist = Checklist(checklist_title = (f"Temp{request.user.id}"), creator = request.user)
        temp_checklist.save()
    item_form = ChecklistItemForm(item_checklist=temp_checklist)
    if request.method == "POST":
        checklist_form = ChecklistForm(data=request.POST, initial={'creator': request.user})
        if checklist_form.is_valid():
            new_checklist = Checklist(
                checklist_title = checklist_form.cleaned_data.get('checklist_title'), 
                document = checklist_form.cleaned_data.get('document'),
                creator = request.user
            )
            new_checklist.save()
            new_checklist.researchers.set(checklist_form.cleaned_data.get('researchers'))
            new_checklist.reviewers.set(checklist_form.cleaned_data.get('reviewers'))
            new_checklist.checklist_users.set(new_checklist.researchers.all().union(new_checklist.reviewers.all()))
            new_checklist.checklistitem_set.set(temp_checklist.checklistitem_set.all())
            temp_checklist.delete()
            return redirect('cl_app:user_checklists')
    else:
        checklist_form = ChecklistForm(initial={'creator': request.user})
    return render(
        request, 
        'cl_app/add_checklist.html', 
        {'checklist_form': checklist_form, 'item_form': item_form, 'temp_checklist': temp_checklist}
    )

@login_required(login_url='user_app:login')
def add_temp_item(request):
    """Adds an item to a checklist that is used to store the checklist items until the user finalises 
    the details of the checklist."""
    temp_checklist = request.user.get_temp_checklist()
    if request.method == "POST":
        item_form = ChecklistItemForm(request.POST, item_checklist=temp_checklist)
        if item_form.is_valid():
            new_item = ChecklistItem(
                item_checklist = temp_checklist,
                item_title = item_form.cleaned_data.get('item_title'),
                time_estimate = item_form.cleaned_data.get('time_estimate')
            )
            new_item.save()
            new_item.dependencies.set(item_form.cleaned_data.get('dependencies'))
    return redirect('cl_app:add_checklist')

@login_required(login_url='user_app:login')
def use_template(request):
    """Changes the items in the temporary checklist to a template list of items."""
    temp_checklist = request.user.get_temp_checklist()
    item_list = TEMPLATE_LIST
    temp_checklist.template_checklist(item_list)
    return redirect('cl_app:add_checklist')

@login_required(login_url='user_app:login')
def remove_temp_item(request, item_id):
    """Removes an item from the temporary storage checklist.

    Parameters
    ----------
    item_id: int
        The id of the temporary checklist item.
    """
    item = get_object_or_404(ChecklistItem, pk=item_id)
    item_checklist = request.user.get_temp_checklist()
    if item.item_checklist == item_checklist:
        item.delete()
    return redirect('cl_app:add_checklist')

@login_required(login_url='user_app:login')
def leave_checklist(request, checklist_id):
    """Allows the user to remove themselves from a checklist's list of users.

    Parameters
    ----------
    checklist_id: int
        The id of the checklist that the user is leaving
    """
    checklist = get_object_or_404(Checklist, pk=checklist_id)
    if checklist.creator != request.user and checklist.checklist_users.contains(request.user):
        checklist.checklist_users.remove(request.user)
        if checklist.researchers.contains(request.user):
            checklist.researchers.remove(request.user)
        if checklist.reviewers.contains(request.user):
            checklist.reviewers.remove(request.user)
    return redirect('cl_app:user_checklists')

@login_required(login_url='user_app:login')
def remove_checklist(request, checklist_id):
    """Allows the creator of a checklist to delete said checklist.

    Parameters
    ----------
    checklist_id: int
        The id of the checklist
    """
    checklist = get_object_or_404(Checklist, pk=checklist_id)
    if checklist.creator == request.user:
        checklist.delete()
    return redirect('cl_app:user_checklists')

@login_required(login_url='user_app:login')
def checklist_view(request, checklist_id):
    """Renders a view of the checklist with the corresponding id.

    Parameters
    ----------
    checklist_id: int
        The id of the checklist
    """
    checklist = get_object_or_404(Checklist, pk=checklist_id)
    if checklist.checklist_users.contains(request.user):
        return render(request, 'cl_app/checklist.html', {'checklist': checklist})
    else:
        return redirect('cl_app:user_checklists')
    
@login_required(login_url='user_app:login')
def open_document(request, checklist_id):
    """Opens the document associated with the checklist in a new tab.

    Parameters
    ----------
    checklist_id: int
        The id of the checklist
    """
    checklist = get_object_or_404(Checklist, pk=checklist_id)
    if checklist.checklist_users.contains(request.user):
        return redirect(checklist.document)
    else:
        return redirect('cl_app:user_checklists')

@login_required(login_url='user_app:login')
def update_item_status(request, item_id):
    """Updates the status of a given checklist item.
    If the status is updated to 'For Review' and a email host has been set, an email is sent notifying the reviewers
    that a review has requested.
    If the status is updated to 'Incomplete', the user will be redirected to a form to provide feedback with.

    Parameters
    ----------
    item_id: int
        The id of the checklist item whose status will be updated.
    """
    item = get_object_or_404(ChecklistItem, pk=item_id)
    checklist = item.item_checklist
    value = int(request.POST.get("status"))
    if (checklist.researchers.contains(request.user) and value == 2) or \
        (checklist.reviewers.contains(request.user) and (value == 1 or value == 3)):
        item.item_status = value
        item.save()
        if value == 2 and EMAIL_HOST_USER != '':
            subject=f"Review Requested for {item.item_title} in {checklist.checklist_title}"
            message=f"{request.user.name} has requested that \"{item.item_title}\" as part of the checklist," +\
                f"\"{checklist.checklist_title}\" be peer reviewed by a reviewer. Login to the checklist webapp for more." 
            if checklist.document != "":
                message += f"\n\nFind the associated document at {checklist.document}"
            send_mail(subject, message, EMAIL_HOST_USER, checklist.reviewer_emails())
        elif value == 3 and EMAIL_HOST_USER != '':
            return redirect('cl_app:send_feedback', item_id=item_id)
        return redirect('cl_app:checklist', checklist_id=checklist.id)
    else:
        return redirect('cl_app:user_checklists')
    
@login_required(login_url='user_app:login')
def send_feedback(request, item_id):
    """Renders a view of the feedback page.
    Upon submission of the form, an email featuring the reviewer's feedback will be sent to the researchers.

    Parameters
    ----------
    item_id: int
        The id of the checklist item whose status will be updated.
    """
    item = get_object_or_404(ChecklistItem, pk=item_id)
    checklist = item.item_checklist
    if checklist.reviewers.contains(request.user):
        if request.method == "POST":
            feedback_form = FeedbackForm(request.POST)
            if feedback_form.is_valid():
                subject = f"Feedback regarding {item.item_title} in {checklist.checklist_title}"
                message = f"{request.user.name} has reviewed \"{item.item_title}\" as part of the checklist, " +\
                    f"\"{checklist.checklist_title}\"and provided the following feedback: " +\
                    f"\n\n{feedback_form.cleaned_data.get('feedback')}"
                if checklist.document != "":
                    message += f"\n\nFind the associated document at {checklist.document}"
                send_mail(subject, message, EMAIL_HOST_USER, checklist.researcher_emails())
                return redirect('cl_app:checklist', checklist_id=checklist.id)
            elif feedback_form.has_error(NON_FIELD_ERRORS, 'charactermin'):
                feedback_form.fields["warning_override"].widget = forms.CheckboxInput()
        else:
            feedback_form = FeedbackForm()
        return render(request, 'cl_app/feedback.html', {'item': item, 'feedback_form': feedback_form})
    else:
        return redirect('cl_app:user_checklists')

@login_required(login_url='user_app:login')
def edit_checklist(request, checklist_id):
    """Renders a view of the edit_checklist page. 
    Upon submission of the form, the checklist will be updated with the new information.

    Parameters
    ----------
    checklist_id: int

sm_app/sm_project/cl_app/templates/cl_app/add_checklist.html
{% extends 'user_app/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <h2 class="pb-2">Checklist Creation</h2>
  <form action="{% url 'cl_app:add_checklist' %}" method="POST" id="checklist">
    {% crispy checklist_form %}
  </form>
  <hr class="mt-2 mb-2">
  <h4 class="pb-2">Checklist Items</h4>
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th scope="col" width="20%">Checklist Item</th>
        <th scope="col" width="12%">Status</th>
        <th scope="col" width="20%">Estimated Finish Date</th>
        <th scope="col" width="28%">Dependencies</th>
        <th scope="col" width="20%">Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for item in temp_checklist.checklistitem_set.all|dictsort:"pk" %}
        <tr>
          <td scope="row">{{ item.item_title }}</td>
          <td>{{ item.get_status }}</td>
          <td>{{ item.time_estimate }}</td>
          <td>{{ item.get_dependencies }}</td>
          <td>
            <div class="col text-center">
              <a href="{% url 'cl_app:remove_temp_item' item.id %}"><button class="btn btn-danger">Delete Item</button>
            </div>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <div class="col text-center pb-3">
    <a href="{% url 'cl_app:use_template' %}"><button class="btn btn-primary">Use Template Checklist</button></a>
  </div>
  <hr class="mt-2 mb-2">
  <h4>Add Checklist Item</h4>
  <form action="{% url 'cl_app:add_temp_item' %}" method="POST" id="item">
    {% crispy item_form %}
  </form>
  <hr class="mt-3 mb-3">
  <div class="form-row">
    <div class="col text-center pb-2">
      <button type="submit" form="checklist" class="btn btn-success">Create Checklist</button>
    </div>
  </div>
  <div class="form-row">
    <div class="col text-center pb-4">
      <a href="{% url 'cl_app:user_checklists' %}"><button class="btn btn-secondary">Back</button></a>
    </div>
  </div>
{% endblock %}

sm_app/sm_project/cl_app/templates/cl_app/checklist.html
{% extends 'user_app/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  {% if checklist in user.researchers.all and checklist in user.reviewers.all %}
    <h2>{{ checklist.checklist_title }}</h2>
  {% elif checklist in user.reviewers.all %}
    <h2>{{ checklist.checklist_title }} - Reviewer View</h2>
  {% else %}
    <h2>{{ checklist.checklist_title }} - Researcher View</h2>
  {% endif %}
  <h4 class="pb-3">Created By: {{ checklist.creator.name }}</h4>
  <div class="row pb-4">
    {% if checklist.document != "" %}
      <div class="col text-center">
        <a href="{% url 'cl_app:open_document' checklist.id %}" target="_blank" rel="noopener noreferrer">
          <button class="btn btn-info">Open Associated Document</button>
        </a>
      </div>
    {% endif %}
    <div class="col text-center">
      <a href="{% url 'cl_app:edit_checklist' checklist.id %}"><button class="btn btn-info">Edit Checklist</button></a>
    </div>
  </div>
  <h4 class="pb-3">Checklist Items</h4>
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th scope="col" width="18%">Checklist Item</th>
        <th scope="col" width="10%">Status</th>
        <th scope="col" width="14%">Estimated Finish Date</th>
        <th scope="col" width="25%">Dependencies</th>
        <th scope="col" width="33%">Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for item in checklist.checklistitem_set.all|dictsort:"pk" %}
        <tr>
          <td scope="row">{{ item.item_title }}</td>
          <td>{{ item.get_status }}</td>
          <td>{{ item.time_estimate }}</td>
          <td>{{ item.get_dependencies }}</td>
          <td>
            <form action="{% url 'cl_app:update_item_status' item.id %}" method="POST">
              {% csrf_token %}
              <div class="row no-gutters">
                {% if checklist in user.researchers.all and item.item_status != 2 and item.dependencies_completed %}
                  <div class="col text-center">
                    <button type="submit" name="status" value="2" class="btn btn-primary">Request Review</button>
                  </div>
                {% elif checklist in user.reviewers.all and item.item_status == 2 %}
                  <div class="col text-center">
                    <button type="submit" name="status" value="1" class="btn btn-success">Mark As Complete</button>
                  </div>
                  <div class="col text-center">
                    <button type="submit" name="status" value="3" class="btn btn-danger">Mark As Incomplete</button>
                  </div>
                {% endif %}
              </div>
            </form>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <div class="col text-center pb-4">
    <a href="{% url 'cl_app:user_checklists' %}"><button class="btn btn-secondary">Back</button></a>
  </div>
{% endblock %}

sm_app/sm_project/cl_app/templates/cl_app/checklist_index.html
{% extends 'user_app/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <h2 class="pb-2">Checklists</h2>
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th scope="col" width="27%">Checklist</th>
        <th scope="col" width="23%">Creator</th>
        <th scope="col" width="50%">Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for checklist in user.checklist_set.all|dictsort:"pk" %}
        <tr>
          <td scope="row">{{ checklist.checklist_title }}</td>
          <td>{{ checklist.creator.name }}</td>
          <td>
            <div class="row no-gutters">
              <div class="col text-center">
                <a href="{% url 'cl_app:checklist' checklist.id %}">
                  <button class="btn btn-primary">Open Checklist</button>
                </a>
              </div>
              <div class="col text-center">
                {% if checklist.creator == user %}
                  <a href="{% url 'cl_app:remove_checklist' checklist.id %}">
                    <button class="btn btn-danger" onclick="return confirm('Are you sure?')">Delete Checklist</button>
                  </a>
                {% else %}
                  <a href="{% url 'cl_app:leave_checklist' checklist.id %}">
                    <button class="btn btn-warning" onclick="return confirm('Are you sure?')">Leave Checklist</button>
                  </a>
                {% endif %}
              </div>
            </div>
          </td>
        </tr>
      {% endfor %}
      <tr>
        <td scope="row" colspan="3">
          <div class="col text-center">
            <a href="{% url 'cl_app:add_checklist' %}"><button class="btn btn-success">Add Checklist</button></a>
          </div>
        </td>
      </tr>
    </tbody>
  </table>
  <div class="col text-center pb-4">
    <a href="{% url 'cl_app:logout' %}"><button class="btn btn-secondary">Logout</button></a>
  </div>
{% endblock %}

sm_app/sm_project/cl_app/templates/cl_app/edit_checklist.html
{% extends 'user_app/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <h2 class="pb-2">Edit {{ checklist.checklist_title }}</h2>
  <form action="{% url 'cl_app:edit_checklist' checklist.id %}" method="POST" id="checklist">
    {% crispy checklist_form %}
  </form>
  <hr class="mt-2 mb-2">
  <h4 class="pb-2">Checklist Items</h4>
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th scope="col" width="20%">Checklist Item</th>
        <th scope="col" width="12%">Status</th>
        <th scope="col" width="20%">Estimated Finish Date</th>
        <th scope="col" width="28%">Dependencies</th>
        <th scope="col" width="20%">Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for item in checklist.checklistitem_set.all|dictsort:"pk" %}
        <tr>
          <td scope="row">{{ item.item_title }}</td>
          <td>{{ item.get_status }}</td>
          <td>{{ item.time_estimate }}</td>
          <td>{{ item.get_dependencies }}</td>
          <td>
            <div class="col text-center">
              <a href="{% url 'cl_app:remove_item' item.id %}"><button class="btn btn-danger">Delete Item</button>
            </div>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <hr class="mt-2 mb-2">
  <h4>Add Checklist Item</h4>
  <form action="{% url 'cl_app:add_item' checklist.id %}" method="POST" id="item">
    {% crispy item_form %}
  </form>
  <hr class="mt-3 mb-3">
  <div class="form-row">
    <div class="col text-center pb-2">
      <button type="submit" form="checklist" class="btn btn-success">Update Checklist</button>
    </div>
  </div>
  <div class="form-row">
    <div class="col text-center pb-4">
      <a href="{% url 'cl_app:user_checklists' %}"><button class="btn btn-secondary">Back</button></a>
    </div>
  </div>
{% endblock %}

sm_app/sm_project/cl_app/templates/cl_app/feedback.html
{% extends 'user_app/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<h2>Provide Feedback</h2>
<p>In the form below, please include detailed feedback on the novelty, potential impact of the research 
  and the overall quality of the paper and give your opinion on the paper as an expert.</p>
<form id="feedback" method="POST">
  {% csrf_token %}
  {{ feedback_form|crispy }}
</form>
<div class="form-row">
  <div class="col text-center pb-4">
    <button type="submit" form="feedback" class="btn btn-success">Submit Feedback</button>
  </div>
  <div class="col text-center pb-4">
    <a href="{% url 'cl_app:checklist' item.item_checklist.id %}"><button class="btn btn-secondary">Skip</button>
  </div>
</div>
{% endblock %}